[workspace]
resolver = "2"
members = [
    "lum",       # Include the lum crate
    "lumal",     # Include the lumal crate
    "examples",  # example programs
    "as_u8_slice_derive", # derive macro for AsU8Slice
]

[profile.dev]
opt-level = 1
codegen-units = 16
lto = "off"
overflow-checks = true
incremental = true

[profile.release]
opt-level = "s"
panic = "unwind"
codegen-units = 1     # TODO: when release only needed
lto = "thin"
overflow-checks = true # TODO: 
# Array bound checks

[profile.dev.package."lum"]
opt-level = 0
incremental = true

[profile.dev.package."lumal"]
opt-level = 0
incremental = true

[profile.release.package."lum"]
opt-level = 3