cargo-features = ["profile-rustflags"]

[workspace]
resolver = "3"
members = ["lum", "lumal", "shaders", "examples", "as_u8_slice_derive"]

[profile.dev]
opt-level = 0
codegen-units = 12
lto = false
panic = "unwind"
overflow-checks = true
incremental = true
debug = true

# Settings for your own packages (lum, lumal, examples)
# These explicitly override the general dev settings to ensure
# low optimization, debug info, and no inlining.
[profile.dev.package.lum]
opt-level = 0
debug = true
inline = "never"
[profile.dev.package.lumal]
opt-level = 0
debug = true
inline = "never"
[profile.dev.package.examples]
opt-level = 0
debug = true
inline = "never"
[profile.dev.package.wgpu]
opt-level = 1
debug = true
inline = "never"

# This wildcard applies to all packages *not* explicitly listed above.
[profile.dev.package."*"]
opt-level = 3 # Optimize dependencies highly
debug = false # No debug info

[profile.release]
opt-level = 3          # "s" is 5 times slower lol. TODO: investigate
panic = "unwind"
codegen-units = 16
lto = false
overflow-checks = true # TODO: unchecked math (UB on overflow)

# Highest possible optimizations
# these profile settings are not a good example to use. They are somewhat internal to see how small can the binary be
# dont forget to build std lib with the project to see good size
[profile.native]
inherits = "release"
opt-level = "s"
codegen-units = 1
lto = "fat"
debug = false
panic = "abort"
overflow-checks = false
strip = true
debug-assertions = false
# [profile.native.package."*"]
# opt-level = "s"

[profile.bench]
inherits = "release"
opt-level = 3
codegen-units = 1
lto = "thin"
debug = false
overflow-checks = false
strip = false

# dont forget to build std lib with the project
# "z" is very slow, but too get the smallest binary...
[profile.natsize]
inherits = "release"
opt-level = "z"
lto = "fat"
codegen-units = 1
debug = false
panic = "abort"
overflow-checks = false
strip = true
[profile.natsize.package."*"]
opt-level = "z"


# TODO: profile package?
# TODO: multiverse cfg?
[profile.distribution]
inherits = "release"
opt-level = 3
lto = "fat"
codegen-units = 1
debug = false
panic = "unwind"
overflow-checks = true
