[alias]     # command aliases
    c = "check"
    t = "test"
    b = "build"
    r = "run"
    br = "build --release"
    brr = "run --release" # yes one extra r.

[build]
    rustflags = [
        # "-C", "link-arg=-fuse-ld=lld",   # Use LLVM's lld linker
        # "-Z", "threads=8"              # Use multithreaded frontend during compilation. Or is it?
    ]

[env]
    RUST_BACKTRACE = "full" # this is what i love in Rust
    
[profile.native.build-override]
    rustflags = [
        "-C", "target-cpu=native",
        # "-C", "link-arg=-fuse-ld=lld",   # Use LLVM's lld linker
        # "-Z", "threads=8"              # Use multithreaded frontend during compilation. Or is it?
        "-Zlocation-detail=none",
        "-Zfmt-debug=none",
    ]
    
[profile.natsize.build-override]
    rustflags = [
        "-C", "target-cpu=native",
        # "-C", "link-arg=-fuse-ld=lld",   # Use LLVM's lld linker
        # "-Z", "threads=8"              # Use multithreaded frontend during compilation. Or is it?
        "-Zlocation-detail=none",
        "-Zfmt-debug=none",
    ]
