[package]
name = "examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
lum = { path = "../lum" }  # Dependency on lum crate
lumal = { path = "../lumal" }  # Dependency on lum crate
vulkanalia = { version = "0.25.0", features = ["libloading", "provisional", "window"] }
vulkanalia-vma = { version = "0.2.0" }
winit = "0.29"
cgmath = "0.18.0"
anyhow = "1"