[package]
    name = "examples"
    version = "0.1.0"
    edition = "2021"
    publish = false

[dependencies]
    lum = { path = "../lum" } # Dependency on lum crate
    shaders = { path = "../shaders" } # Dependency on shaders crate (just compiles all of them)
    winit = "0.30.8"
    anyhow = "1"
    flame = "0.2.2"