cargo-features = ["edition2024"]

[package]
name = "shaders"
version = { workspace = true }
edition = { workspace = true }
readme = { workspace = true }

[features]
vk_backend = []
wgpu_backend = []

[lib]
path = "lib.rs"

[build-dependencies]
cargo-gpu = { git = "https://github.com/rust-gpu/cargo-gpu" }
